#!/bin/sh

if [ ! -f ./json-simple.jar ]; then
  echo "To run the tests you must download json-simple.jar from http://code.google.com/p/json-simple/"
  exit 1
fi

test_server="$1"
test_api_key="$2"

if [ ! "$test_server" ] || [ ! "$test_api_key" ]; then
  echo "You must provide a test server and test api key as arguments"
  exit 1
fi

# Compile etherpad_lite_client.jar
cd `dirname $0`/../src
javac -classpath ../test/json-simple.jar org/etherpad_lite_client/*.java
jar cf etherpad_lite_client.jar org/etherpad_lite_client/*.class
mv etherpad_lite_client.jar ../test

# Compile test program
cd ../test
javac -classpath etherpad_lite_client.jar EPLiteTest.java

# Run tests
java -classpath ./:json-simple.jar:etherpad_lite_client.jar EPLiteTest "$test_server" "$test_api_key"
